---
# TitleJoin By Teunboeke
# Configuration File

# Set true or false to enable or disable titles on join
Title-on-join: true

# Text Configuration
# You may use & as your color codes.
Title: "you can edit this in the "
Subtitle: "config!"

# Time Configuration
# 20 ticks = 1 second
Fade-In: 20
Lenght: 20
Fade-Out: 20
...
